package uparis.diamanthamdi.backend.model.fire.generator;

import java.security.SecureRandom;

import uparis.diamanthamdi.backend.model.grid.Grid;

/**
 * Class to generate fire on a grid.
 * 
 * The fire is generated by setting random cells on fire.
 */
public class FireGenerator {
    private static final SecureRandom random = new SecureRandom();
    /** The width of the grid. */
    private final int width;
    /** The height of the grid. */
    private final int height;
    /** The grid to generate the fire on. */
    private final Grid grid;

    /**
     * Creates a new fire generator with the given grid.
     *
     * @param grid The grid to generate the fire on.
     */
    public FireGenerator(final Grid grid) {
        this.grid = grid;
        this.width = grid.getWidth();
        this.height = grid.getHeight();
    }

    /**
     * Generates the fire on the grid.
     */
    public void generateFire() {
        int cellsOnFire = 10;
        while (cellsOnFire > 0) {
            if (generateRandomFire()) {
                cellsOnFire--;
            }
        }
    }

    /**
     * Generates a random fire on the grid.
     *
     * @return True if a fire was generated, false otherwise.
     */
    private boolean generateRandomFire() {
        int x = random.nextInt(width);
        int y = random.nextInt(height);

        if (this.grid.getCell(x, y).isOnFire()) {
            return false;
        }

        int intensity = random.nextInt(9) + 1;
        this.grid.setFire(x, y, intensity);

        return true;
    }
}
